version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arceon-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=8080
    restart: unless-stopped 